server:
  port: 8000

web:
  domain: http://localhost

spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true

  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15959690591
    url: jdbc:mysql://localhost:3306/fu_cloud?useSSL=true&useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.fucloud.fucloudbackend.dao: debug

